title: Megh Dave
logo: ./assets/img/IMG_1417_Original.jpeg
#logo: /assets/img/IMG_1417_Original.png
#description: A showcase of my projects and skills
#show_downloads: true
theme: jekyll-theme-minimal

# Add your social links
email: mdave5@horizon.csueastbay.edu
linkedin_username: megh-dave
github_username: Megh-Dave

# Custom links (add as many as you like)
social_links:
  - label: "Resume"
    icon: "fas fa-file-pdf"
    url: "./assets/Megh_Dave_Resume.pdf"
